### ISSUE TITLE
ModTek died

### ISSUE THREAD

**Issue by Orc88** [BattletechModders/ModTek#201] opened 2022-08-14 19:12 UTC
Hello, I've tried installing modtek a few times and at startup I get a 'modtek died' notice. I get the following in the log: 

8/14/2022 1:57:01 PM ModTek v2.0.7+1.Branch.master.Sha.7365e5d02d0d34ea3ee375c19e44f5212c7dd055 (2022-06-04)
--------------------------------------------------------------------------------
ProductName: BATTLETECH
ProductVersion: 1.9.1
Platform: STEAM
BuildRevision: cdbbe62917b8c241c9d22c8540fee15595373c89
BuildBranch: live
BuildDate: 2020-02-26T07:33:27
BuildStamp: 200226-live-cdbbe62
BuildNumber: 686R

[LOG] Applying ModTek harmony patches
[LOG] UILookAndColorConstants fields:245
[LOG] SQLite version 3.16.2
[LOG] Building new load order!
[ERROR] Uncaught ModTek exception!: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
	  at System.Collections.Generic.Dictionary`2[TKey,TValue].get_Item (TKey key) [0x0001e] in <d7ac571ca2d04b2f981d0d886fa067cf>:0 
	  at ModTek.Util.LoadOrder.CreateLoadOrder (System.Collections.Generic.Dictionary`2[TKey,TValue] modDefs, System.Collections.Generic.List`1[ModTek.ModDefEx]& notLoaded, System.Collections.Generic.List`1[T] cachedOrder) [0x00146] in <844c5e60f272409fbe6c67702b09d06e>:0 
	  at ModTek.Features.Manifest.Mods.ModDefsDatabase.SetupModLoadOrderAndRemoveUnloadableMods () [0x00011] in <844c5e60f272409fbe6c67702b09d06e>:0 
	  at ModTek.Features.Manifest.Mods.ModDefsDatabase+<InitModsLoop>d__8.MoveNext () [0x000e8] in <844c5e60f272409fbe6c67702b09d06e>:0 
	  at ModTek.UI.ProgressPanel+ProgressBarLoadingBehavior+<RunWorkList>d__20.MoveNext () [0x0007b] in <844c5e60f272409fbe6c67702b09d06e>:0 
[LOG] Done. Elapsed running time: 0.9169064 seconds

thanks

**Comment by CptMoore** [comment] 2022-09-22 20:22
Tried to understand the error a few times now, and couldn't really reproduce it.
Might be an issue with how cached/previous load orders is being processed within the code.
Could also be the name handling.
If you still have this error, I could create a ModTek dll with more log information to figure this out.

**Comment by cescudero95** [comment] 2023-03-01 10:15
Hi there,

I'm currently experiencing this error as well.  Have deleted the .modtek folder, repaired battletech files a couple of times and tried with both versions 2.0.7 and 3.1.1.4, but same result.

**Comment by CptMoore** [comment] 2023-03-01 17:38
please try again with 
[ModTek.zip](https://github.com/BattletechModders/ModTek/files/10863866/ModTek.zip)
it logs more when going through the load order

**Comment by CptMoore** [comment] 2023-05-19 11:06
Closing due to the supplied special modtek supplied above being outdated

**Closed by CptMoore** 2023-05-19 11:06 UTC
Labels: bug, help wanted
